### ISSUE TITLE
[feature request] Add a button to toggle automatic brightness

### ISSUE THREAD

**Issue by gitwah** [do-sch/gnome-shell-brightness-panel-menu-indicator#2]
Hi, thanks for this useful extension. It would be perfect for me if it included a button next to the brightness slider for enabling and disabling automatic brightness. 
Many newer notebooks and convertibles have a built-in sensor that allows an automatic adjustment of the screen brightness. With gnome, this generally works pretty well (and can be toggled in gnome-control-center under Power), but in darker conditions it's sometimes a bit erratic. A faster toggle via panel would be nice.

**Comment by do-sch** [comment]
I actually only use the extension on the desktop PC and I don't have a notebook with autobrightness myself. I couldn't test it.

If you ask me, it would be better if a separate extension is written for the desired functionality. It doesn't really fit in here.
