### ISSUE TITLE
error: klass is undefined

### ISSUE THREAD

**Issue by rcmz** [do-sch/gnome-shell-brightness-panel-menu-indicator#3]
Hello,

Updated my Manjaro and got a "klass is undefined" error
I look a bit through your code and saw that the work "klass" appeared 0 times so I'm a bit confused

**Comment by do-sch** [comment]
When updating to Gnome 43 I must have broken something in the backwards compatibility. It may be a day before the fix ends up on extensions.gnome.org. But you can also pull it from Git beforehand and install it directly.

**Comment by rcmz** [comment]
I can confirm the fix works, what a quick reaction !
